name: Webpack build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build
        working-directory: tp1
        run: |
          npm install
          npm run build
